oauth:
  google:
    client:
      id: prod configured in Kubernetes ConfigMap. local configured as VM argument

## MySQL Database
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/home-stack
    username: root
    password: password
    driver-class-name:  com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size:  10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: true

email:
  url: http://home-email-service:8081/home/email/send
  token:
    issuer: home-stack-auth
    url: http://home-auth-service:8081/home/auth/home/token/generate
    scope: home_api_rw
    audience: home-stack-email
