spring:
  application:
    name: home-auth-service
server:
  port: 8081
  servlet:
    context-path: /home/auth

oauth:
  google:
    client:
      id: prod configured in Kubernetes ConfigMap. local configured as VM argument

application:
  id: home-stack-auth
  security:
    jwt:
      access-token:
        validity: 1800 # 30 minutes
      refresh-token:
        validity: 172800 # 2 days